version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-76-136.compute-1.amazonaws.com
            database: deiprkmnrf15n2
            # schema: public
            user: meuioxlyyxjhao
            password: da1861416c0756a384d1374d6474c36b4fa506ee8cc71c15e70e44cd3e2c997a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true